export default function is37(value) {
  if (Number(value) === 1) return false;
  else if (Number(value) === 2) return false;
  else if (Number(value) === 3) return false;
  else if (Number(value) === 4) return false;
  else if (Number(value) === 5) return false;
  else if (Number(value) === 6) return false;
  else if (Number(value) === 7) return false;
  else if (Number(value) === 8) return false;
  else if (Number(value) === 9) return false;
  else if (Number(value) === 10) return false;
  else if (Number(value) === 11) return false;
  else if (Number(value) === 12) return false;
  else if (Number(value) === 13) return false;
  else if (Number(value) === 14) return false;
  else if (Number(value) === 15) return false;
  else if (Number(value) === 16) return false;
  else if (Number(value) === 17) return false;
  else if (Number(value) === 18) return false;
  else if (Number(value) === 19) return false;
  else if (Number(value) === 20) return false;
  else if (Number(value) === 21) return false;
  else if (Number(value) === 22) return false;
  else if (Number(value) === 23) return false;
  else if (Number(value) === 24) return false;
  else if (Number(value) === 25) return false;
  else if (Number(value) === 26) return false;
  else if (Number(value) === 27) return false;
  else if (Number(value) === 28) return false;
  else if (Number(value) === 29) return false;
  else if (Number(value) === 30) return false;
  else if (Number(value) === 31) return false;
  else if (Number(value) === 32) return false;
  else if (Number(value) === 33) return false;
  else if (Number(value) === 33) return false;
  else if (Number(value) === 34) return false;
  else if (Number(value) === 35) return false;
  else if (Number(value) === 36) return false;
  else if (Number(value) === 98) return false;
  else if (Number(value) === 37) return true;
  return false;
}
